name: razer-control
base: core22
version: '0.1.0'
summary: Razer Laptop Control Revived
description: |
  A Linux userspace application to control Razer Blade laptops. 
  No kernel modules (DKMS) required!
  Supports Fan control, Power modes, Logo LED, and Battery Health Optimizer.

grade: stable
confinement: strict

plugs:
  hidraw:
  raw-usb:
  system-observe:
  hardware-observe:
  
parts:
  razer-control:
    plugin: rust
    source: .
    build-packages:
      - libusb-1.0-0-dev
      - libdbus-1-dev
      - libhidapi-dev
      - libgtk-3-dev
      - pkg-config
    stage-packages:
      - libusb-1.0-0
      - libdbus-1-3
      - libhidapi-hidraw0
      - libgtk-3-0

apps:
  razer-settings:
    command: bin/razer-settings
    plugs: [hidraw, raw-usb, system-observe, hardware-observe, desktop, desktop-legacy, wayland, x11]
  
  razer-cli:
    command: bin/razer-cli
    plugs: [hidraw, raw-usb, system-observe, hardware-observe]

  daemon:
    command: bin/daemon
    daemon: simple
    plugs: [hidraw, raw-usb, system-observe, hardware-observe]
